#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D source_depth;
layout(rg32f, set = 0, binding = 1) uniform writeonly image2D destination_mip;

layout(push_constant) uniform depth_pyramid_constants
{
    ivec2 destination_extent;
    ivec2 source_extent;
    int source_mip;
} constants;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(pixel, constants.destination_extent)))
        return;
    if (constants.source_mip < 0)
    {
        float depth = texelFetch(source_depth, pixel, 0).r;
        imageStore(destination_mip, pixel, vec4(depth, depth, 0.0, 0.0));
        return;
    }
    ivec2 source = pixel * 2;
    ivec2 maximum_source = max(constants.source_extent - ivec2(1), ivec2(0));
    ivec2 maximum_offset = ivec2(1);
    if (pixel.x == constants.destination_extent.x - 1 && (constants.source_extent.x & 1) != 0)
        maximum_offset.x = 2;
    if (pixel.y == constants.destination_extent.y - 1 && (constants.source_extent.y & 1) != 0)
        maximum_offset.y = 2;
    float nearest_depth = 1.0;
    float farthest_depth = 0.0;
    for (int y = 0; y <= 2; ++y)
    {
        for (int x = 0; x <= 2; ++x)
        {
            if (x > maximum_offset.x || y > maximum_offset.y)
                continue;
            vec2 depth = texelFetch(source_depth, min(source + ivec2(x, y), maximum_source),
                                    constants.source_mip).rg;
            nearest_depth = min(nearest_depth, depth.r);
            farthest_depth = max(farthest_depth, depth.g);
        }
    }
    imageStore(destination_mip, pixel, vec4(nearest_depth, farthest_depth, 0.0, 0.0));
}
