export type RenderGraphResource = {
  name: string;
  format: string;
  firstPass: number;
  lastPass: number;
  physicalResource: number;
  estimatedBytes: number;
  aliased?: boolean;
};

export type RenderGraphTransition = {
  resource: string;
  before: string;
  after: string;
  beforePass: number;
  afterPass: number;
  beforeQueue: string;
  afterQueue: string;
};

export type EditorDiagnosticsSnapshot = {
  frameIndex: number;
  summary: string;
  passes: Array<{ name: string; milliseconds: number }>;
  timingsAvailable: boolean;
  graph: {
    executedPasses: string[];
    culledPasses?: string[];
    resources?: RenderGraphResource[];
    transitions?: RenderGraphTransition[];
    submissions?: Array<{ queue: string; passCount: number; waitCount: number; signalValue: number }>;
    histories?: Array<{ key: string; length: number; invalidated: boolean }>;
    resourceCount: number;
    physicalResourceCount?: number;
    aliasCount?: number;
    barrierCount: number;
    estimatedTransientBytes: number;
  };
  renderer: {
    path: string;
    renderScale: number;
    qualityTier: string;
    targetFrameMilliseconds: number;
    fallbackReasons: string[];
  };
  environment: {
    enabled: boolean;
    skyVisible: boolean;
    affectsLighting: boolean;
    source: string;
    qualityPath: string;
    atmosphereLutState: string;
    lightingState: string;
    cloudShadowResolution: number;
    fallback: string;
  };
  indirectLighting: {
    enabled: boolean;
    tracePath: string;
    traceScale: number;
    giRays: number;
    reflectionRays: number;
    surfaceCards: number;
    residentSurfacePages: number;
    residentDistanceFieldPages: number;
    dirtyRegions: number;
    surfaceUpdates: number;
    radianceProbeUpdates: number;
    residentBytes: number;
    budgetBytes: number;
    screenHitRate: number;
    softwareHitRate: number;
    hardwareHitRate: number;
    fallback: string;
  };
  shadows: {
    cascades: number;
    directionalResolution: number;
    localAtlasResolution: number;
    localAllocations: number;
    localOccupiedTexels: number;
    localEvictions: number;
    localResolutionReductions: number;
    shadowedPointLights: number;
    shadowedSpotLights: number;
    staticCasters: number;
    dynamicCasters: number;
    localCacheHits: number;
    localCacheMisses: number;
    staticCacheHit: boolean;
    screenSpaceShadows: boolean;
    virtualShadowMaps: boolean;
    virtualAddressSpaces: number;
    virtualPageCapacity: number;
    virtualResidentPages: number;
    virtualDirtyPages: number;
    virtualRenderedPages: number;
    virtualReusedPages: number;
    virtualEvictions: number;
    virtualParentFallbacks: number;
    virtualFailedRequests: number;
    virtualMemoryBytes: number;
    fallback: string;
  };
  gpuScene?: {
    enabled: boolean;
    hzbOcclusion: boolean;
    historyValid: boolean;
    capacity: number;
    activeInstances: number;
    uploadedInstances: number;
    uploadedRanges: number;
    uploadedBytes: number;
    geometryTableEntries: number;
    materialTableEntries: number;
    textureTableEntries: number;
    samplerTableEntries: number;
    skinPaletteTableEntries: number;
    sharedVertexHeapBytes: number;
    sharedIndexHeapBytes: number;
    candidateInstances: number;
    visibleInstances: number;
    frustumRejected: number;
    distanceRejected: number;
    occlusionRejected: number;
    activePipelineBins: number;
    indirectCommands: number;
    overflowRecords: number;
    cpuSubmissions: number;
    fallback: string;
  };
  textureStreaming?: {
    gpuBudgetBytes: number;
    gpuResidentBytes: number;
    cpuBudgetBytes: number;
    cpuCachedBytes: number;
    uploadBudgetBytes: number;
    uploadedBytes: number;
    ioReadBytes: number;
    ioFailedBytes: number;
    ioCompletedReads: number;
    ioFailedReads: number;
    ioInFlightReads: number;
    ioLatencyMilliseconds: number;
    uploadLatencyMilliseconds: number;
    streamedTextures: number;
    virtualTextures: number;
    residentMips: number;
    residentPages: number;
    requestedMips: number;
    requestedPages: number;
    failedMips: number;
    failedPages: number;
    evictions: number;
    feedbackOverflow: number;
    parentFallbacks: number;
    cacheHitRate: number;
    overBudget: boolean;
    fallback: string;
    resources: Array<{
      resourceIndex: number;
      resourceGeneration: number;
      contentGeneration: number;
      authoredMode: 'resident' | 'streamed_mips' | 'virtual_tiles';
      resolvedMode: 'resident' | 'streamed_mips' | 'virtual_tiles';
      desiredMip: number;
      residentMip: number;
      tailFirstMip: number;
      residentBytes: number;
      forcedMip: number | null;
    }>;
  };
};
