import type { ArcBuildSnapshot } from '../../../common/buildTypes';
import type { EditorSettingsSnapshot, SourceControlSnapshot } from '../../../common/editorWorkflowTypes';
import type { ArcAiGatewayStatus } from '../../../preload/preload';
import type { HostWorldEnvironment } from '../environment/environmentTypes';
import type { InspectorEntitySnapshot } from '../inspector/inspectorTypes';
import type { ProfilerSnapshot } from '../profiler/ProfilerPanel';
import type { ProjectSnapshot } from '../services/editorHostTypes';
import type { EditorDiagnosticsSnapshot } from '../tools/toolTypes';

export const panelProjectFixture: ProjectSnapshot = {
  name: 'Mountain Village',
  root: 'C:/Projects/MountainVillage',
  assetRoot: 'C:/Projects/MountainVillage/Assets',
  activeScene: 'Assets/Scenes/MountainVillage.arcscene',
  scene: [
    {
      id: '1842:7',
      guid: 'entity-cabin-01',
      name: 'Cabin_01',
      kind: 'mesh',
      active: true,
      visible: true,
      components: ['Transform', 'Mesh Renderer'],
      transform: {
        position: { x: 12.5, y: 4, z: -8.25 },
        rotation: { x: 0, y: 35, z: 0 },
        scale: { x: 1, y: 1, z: 1 },
      },
    },
    {
      id: '18:2',
      guid: 'entity-sun',
      name: 'Sun',
      kind: 'light',
      active: true,
      visible: true,
      components: ['Transform', 'Directional Light'],
    },
    {
      id: '21:3',
      guid: 'entity-camera',
      name: 'Main Camera',
      kind: 'camera',
      active: true,
      visible: true,
      components: ['Transform', 'Camera'],
    },
    {
      id: '100:1',
      guid: 'folder-environment',
      name: 'Environment',
      kind: 'folder',
      active: true,
      visible: true,
      children: [
        {
          id: '101:1',
          guid: 'entity-pines',
          name: 'PineCluster_A',
          kind: 'mesh',
          active: true,
          visible: true,
          components: ['Transform', 'Mesh Renderer'],
        },
        {
          id: '102:1',
          guid: 'entity-rocks',
          name: 'RockFormation_02',
          kind: 'mesh',
          active: true,
          visible: true,
          components: ['Transform', 'Mesh Renderer'],
        },
      ],
    },
  ],
  assets: [
    {
      id: 'mesh-cabin',
      guid: 'asset-mesh-cabin',
      name: 'SM_Cabin',
      path: 'Assets/Environment/Cabins/SM_Cabin.glb',
      kind: 'mesh',
      status: 'ready',
      scope: 'project',
      typeId: 'arc.mesh',
      importerId: 'gltf',
      residency: 'device',
      generation: 4,
      dependencies: ['asset-material-wood'],
      reverseDependencies: [],
    },
    {
      id: 'material-wood',
      guid: 'asset-material-wood',
      name: 'M_Wood_Logs',
      path: 'Assets/Materials/M_Wood_Logs.arcmat',
      kind: 'material',
      status: 'ready',
      scope: 'project',
      typeId: 'arc.material',
      importerId: 'material',
      residency: 'device',
      generation: 7,
      dependencies: ['asset-texture-bark'],
      reverseDependencies: ['asset-mesh-cabin'],
    },
    {
      id: 'texture-bark',
      guid: 'asset-texture-bark',
      name: 'T_Bark_Albedo',
      path: 'Assets/Textures/T_Bark_Albedo.png',
      kind: 'texture',
      status: 'ready',
      scope: 'project',
      typeId: 'arc.texture2d',
      importerId: 'image',
      residency: 'device',
      generation: 2,
    },
    {
      id: 'prefab-cabin',
      guid: 'asset-prefab-cabin',
      name: 'PF_Cabin',
      path: 'Assets/Prefabs/PF_Cabin.arcprefab',
      kind: 'prefab',
      status: 'ready',
      scope: 'project',
      typeId: 'arc.prefab',
      importerId: 'prefab',
      residency: 'source',
      generation: 5,
    },
    {
      id: 'shader-pbr',
      guid: 'asset-shader-pbr',
      name: 'pbr_lit.hlsl',
      path: 'Assets/Shaders/pbr_lit.hlsl',
      kind: 'shader',
      status: 'ready',
      scope: 'project',
      typeId: 'arc.shader',
      importerId: 'hlsl',
      residency: 'source',
      generation: 9,
    },
  ],
  console: [
    { id: 'log-1', level: 'info', source: 'editor', message: 'Mountain Village opened.', timestamp: '23:17:04' },
    { id: 'log-2', level: 'info', source: 'assets', message: 'Imported SM_Cabin.glb in 42 ms.', timestamp: '23:17:05' },
    {
      id: 'log-3',
      level: 'warning',
      source: 'renderer',
      message: 'Shadow atlas occupancy reached 78%.',
      timestamp: '23:17:06',
    },
    {
      id: 'log-4',
      level: 'debug',
      source: 'render-graph',
      message: 'Frame graph compiled: 18 passes.',
      timestamp: '23:17:08',
    },
  ],
  renderStats: {
    fps: 60,
    frameTimeMs: 16.67,
    drawCalls: 1842,
    triangles: 3_840_220,
    visibleEntities: 418,
    lights: 6,
    gpuMemoryMb: 4280,
  },
};

export const panelInspectorFixture: InspectorEntitySnapshot = {
  entity: { index: 1842, generation: 7 },
  selectionCount: 1,
  selectedGuids: ['entity-cabin-01'],
  name: 'Cabin_01',
  tag: 'Untagged',
  active: true,
  renderLayerMask: 1,
  mobility: 'static',
  transform: {
    position: { x: 12.5, y: 4, z: -8.25 },
    rotationDegrees: { x: 0, y: 35, z: 0 },
    scale: { x: 1, y: 1, z: 1 },
    rotationQuaternion: { x: 0, y: 0.300706, z: 0, w: 0.953717 },
  },
  camera: null,
  light: null,
  meshRenderer: {
    representation: 'auto',
    visible: true,
    castsShadows: true,
    receivesShadows: true,
    shadowLodBias: 0,
    maximumShadowDistance: 200,
    baseColorTint: { x: 0.72, y: 0.48, z: 0.28, w: 1 },
    hasMaterial: true,
    assetBackedMaterial: true,
    materialName: 'M_Wood_Logs',
    materialPath: 'Assets/Materials/M_Wood_Logs.arcmat',
  },
  terrain: null,
  prefab: {
    prefabGuid: 'asset-prefab-cabin',
    prefabPath: 'Assets/Prefabs/PF_Cabin.arcprefab',
    overrideCount: 2,
    sourceMissing: false,
    overrides: [],
  },
  components: [
    { kind: 'transform', label: 'Transform', editable: true },
    { kind: 'meshRenderer', label: 'Mesh Renderer', editable: true },
    { kind: 'prefab', label: 'Prefab', editable: true },
  ],
  projectComponents: [],
};

export const panelDiagnosticsFixture: EditorDiagnosticsSnapshot = {
  frameIndex: 4821,
  summary: 'Deferred + virtual geometry',
  passes: [
    { name: 'DepthPrepass', milliseconds: 0.62 },
    { name: 'GBuffer', milliseconds: 1.34 },
    { name: 'Lighting', milliseconds: 2.12 },
    { name: 'Tonemap', milliseconds: 0.31 },
  ],
  timingsAvailable: true,
  graph: {
    executedPasses: ['DepthPrepass', 'GBuffer', 'Lighting', 'Tonemap'],
    resources: [
      { name: 'SceneDepth', format: 'D32', firstPass: 0, lastPass: 2, physicalResource: 0, estimatedBytes: 16_777_216 },
      { name: 'GBufferA', format: 'RGBA8', firstPass: 1, lastPass: 2, physicalResource: 1, estimatedBytes: 33_554_432 },
      {
        name: 'HDRColor',
        format: 'RGBA16F',
        firstPass: 2,
        lastPass: 3,
        physicalResource: 2,
        estimatedBytes: 67_108_864,
      },
    ],
    transitions: [
      {
        resource: 'SceneDepth',
        before: 'DepthWrite',
        after: 'ShaderRead',
        beforePass: 0,
        afterPass: 1,
        beforeQueue: 'graphics',
        afterQueue: 'graphics',
      },
      {
        resource: 'HDRColor',
        before: 'RenderTarget',
        after: 'ShaderRead',
        beforePass: 2,
        afterPass: 3,
        beforeQueue: 'graphics',
        afterQueue: 'graphics',
      },
    ],
    resourceCount: 11,
    barrierCount: 24,
    estimatedTransientBytes: 156_237_824,
  },
  renderer: {
    path: 'Deferred',
    renderScale: 1,
    qualityTier: 'High',
    targetFrameMilliseconds: 16.67,
    fallbackReasons: [],
  },
  environment: {
    enabled: true,
    skyVisible: true,
    affectsLighting: true,
    source: 'Physical Atmosphere',
    qualityPath: 'High',
    atmosphereLutState: 'Ready',
    lightingState: 'Ready',
    cloudShadowResolution: 1024,
    fallback: '',
  },
  indirectLighting: {
    enabled: true,
    tracePath: 'Hybrid software / hardware',
    traceScale: 0.5,
    giRays: 824_000,
    reflectionRays: 168_000,
    surfaceCards: 2184,
    residentSurfacePages: 1960,
    residentDistanceFieldPages: 842,
    dirtyRegions: 3,
    surfaceUpdates: 34,
    radianceProbeUpdates: 48,
    residentBytes: 428_000_000,
    budgetBytes: 536_870_912,
    screenHitRate: 0.61,
    softwareHitRate: 0.31,
    hardwareHitRate: 0.08,
    fallback: '',
  },
  shadows: {
    cascades: 4,
    directionalResolution: 2048,
    localAtlasResolution: 4096,
    localAllocations: 17,
    localOccupiedTexels: 13_107_200,
    localEvictions: 0,
    localResolutionReductions: 1,
    shadowedPointLights: 3,
    shadowedSpotLights: 2,
    staticCasters: 224,
    dynamicCasters: 18,
    localCacheHits: 91,
    localCacheMisses: 7,
    staticCacheHit: true,
    screenSpaceShadows: true,
    virtualShadowMaps: true,
    virtualAddressSpaces: 4,
    virtualPageCapacity: 16384,
    virtualResidentPages: 4820,
    virtualDirtyPages: 36,
    virtualRenderedPages: 36,
    virtualReusedPages: 4784,
    virtualEvictions: 12,
    virtualParentFallbacks: 3,
    virtualFailedRequests: 0,
    virtualMemoryBytes: 402653184,
    fallback: '',
  },
};

export const panelBuildFixture: ArcBuildSnapshot = {
  revision: 12,
  state: 'succeeded',
  configuration: 'Development',
  buildRequired: false,
  reloadRequired: false,
  restartRequired: false,
  diagnostics: [
    { sequence: 1, severity: 'info', category: 'compiler', message: 'Compiled game module in 2.6s.' },
    {
      sequence: 2,
      severity: 'warning',
      category: 'compiler',
      message: 'Unused material parameter "SnowAmount".',
      file: 'Game/Materials/CabinMaterial.cpp',
      line: 84,
      column: 11,
    },
  ],
  startedAt: '2026-08-15T23:17:03-07:00',
  completedAt: '2026-08-15T23:17:08-07:00',
  command: 'cmake --build build --config Development',
};

const profilerBase = {
  memory: {
    bytes: 1_486_000_000,
    softLimit: 2_147_483_648,
    hardLimit: 3_221_225_472,
    pressureEvents: 0,
    domains: [
      {
        domain: 'Renderer',
        bytes: 834_000_000,
        peakBytes: 910_000_000,
        softLimit: 1_073_741_824,
        hardLimit: 1_610_612_736,
        pressure: false,
      },
      {
        domain: 'Assets',
        bytes: 412_000_000,
        peakBytes: 488_000_000,
        softLimit: 805_306_368,
        hardLimit: 1_073_741_824,
        pressure: false,
      },
    ],
    groups: [
      {
        domain: 'Renderer',
        tag: 'VirtualGeometry',
        worldId: 1,
        threadId: 4,
        stackId: 18,
        allocationCount: 284,
        bytes: 418_000_000,
      },
      {
        domain: 'Renderer',
        tag: 'RenderGraph',
        worldId: 1,
        threadId: 4,
        stackId: 24,
        allocationCount: 81,
        bytes: 168_000_000,
      },
      {
        domain: 'Assets',
        tag: 'Textures',
        worldId: 1,
        threadId: 2,
        stackId: 7,
        allocationCount: 129,
        bytes: 302_000_000,
      },
    ],
  },
  scheduler: {
    submitted: 18_420,
    completed: 18_392,
    stolen: 842,
    cancelled: 2,
    failed: 0,
    queued: 28,
    droppedEvents: 0,
    jobs: [
      {
        sequence: 1,
        name: 'CullVirtualGeometry',
        priority: 'high',
        affinity: 'worker',
        status: 'completed',
        threadId: 4,
        queuedNanoseconds: 1_000,
        startedNanoseconds: 2_000,
        completedNanoseconds: 286_000,
      },
      {
        sequence: 2,
        name: 'BuildLightGrid',
        priority: 'normal',
        affinity: 'worker',
        status: 'completed',
        threadId: 6,
        queuedNanoseconds: 2_000,
        startedNanoseconds: 6_000,
        completedNanoseconds: 182_000,
      },
    ],
  },
};

export const panelProfilerFixtures: ProfilerSnapshot[] = [
  { timestampNanoseconds: 1_000_000_000, ...profilerBase },
  {
    timestampNanoseconds: 1_016_670_000,
    memory: { ...profilerBase.memory, bytes: 1_512_000_000 },
    scheduler: { ...profilerBase.scheduler, submitted: 18_512, completed: 18_486, queued: 26 },
  },
  {
    timestampNanoseconds: 1_033_340_000,
    memory: { ...profilerBase.memory, bytes: 1_498_000_000 },
    scheduler: { ...profilerBase.scheduler, submitted: 18_604, completed: 18_580, queued: 24 },
  },
];

export const panelGatewayFixture: ArcAiGatewayStatus = {
  enabled: true,
  endpoint: 'http://127.0.0.1:27184',
  discoveryFile: '.arc/ai-gateway.json',
  protocolVersion: 1,
  sceneRevision: 184,
  worldEpoch: 12,
  frameRevision: 4821,
  eventSequence: 992,
  clients: [
    { id: 'codex-local', name: 'Codex', connectedAt: '23:09:12', lastSeenAt: '23:17:08' },
    { id: 'qa-agent', name: 'QA Agent', connectedAt: '23:13:44', lastSeenAt: '23:17:07' },
  ],
  pendingEditRequests: [],
  activeEditSession: null,
  lastCommittedEdit: {
    clientId: 'codex-local',
    label: 'Adjust cabin material roughness',
    sceneRevision: 184,
    committedAt: '23:16:42',
  },
  viewportLease: null,
  audit: [
    {
      sequence: 991,
      timestamp: '23:16:42',
      clientId: 'codex-local',
      category: 'edit',
      operation: 'material.update',
      succeeded: true,
      detail: 'Committed scene revision 184',
    },
    {
      sequence: 992,
      timestamp: '23:17:02',
      clientId: 'qa-agent',
      category: 'query',
      operation: 'scene.snapshot',
      succeeded: true,
      detail: 'Returned 418 visible entities',
    },
  ],
};

export const panelWorldEnvironmentFixture: HostWorldEnvironment = {
  entity: { index: 8, generation: 1 },
  enabled: true,
  skyVisible: true,
  affectLighting: true,
  skySource: 'physicalAtmosphere',
  solidColor: { x: 0.16, y: 0.22, z: 0.31 },
  hdriPath: '',
  hdriRotationDegrees: 0,
  radianceIntensity: 1,
  planetRadius: 6_360_000,
  atmosphereRadius: 6_460_000,
  rayleighStrength: 1,
  mieStrength: 1,
  ozoneStrength: 1,
  atmosphereTint: { x: 1, y: 1, z: 1 },
  groundAlbedo: { x: 0.18, y: 0.19, z: 0.16 },
  mieAnisotropy: 0.8,
  rayleighScaleHeight: 8000,
  mieScaleHeight: 1200,
  multiScatteringFactor: 1,
  exposure: 0,
  sunDiskSize: 1,
  sunDiskIntensity: 1,
  sunMode: 'manualLight',
  timeMode: 'fixed',
  latitudeDegrees: 37.62,
  longitudeDegrees: -122.41,
  northOffsetDegrees: 0,
  year: 2026,
  month: 8,
  day: 15,
  localTimeHours: 16.5,
  utcOffsetHours: -7,
  playing: false,
  loopDay: true,
  timeScale: 60,
  automaticSunLight: true,
  sunIntensityMultiplier: 1,
  sunTemperatureMultiplier: 1,
  moonEnabled: true,
  automaticMoonPhase: true,
  moonPhase: 0.62,
  moonIntensity: 0.12,
  moonAngularRadiusDegrees: 0.26,
  starsEnabled: true,
  starDensity: 0.65,
  starIntensity: 0.7,
  starTwinkle: 0.15,
  cloudsEnabled: true,
  cloudShadows: true,
  cumulus: {
    enabled: true,
    coverage: 0.34,
    density: 0.62,
    altitude: 1800,
    thickness: 2200,
    scale: 1,
    detail: 0.72,
    softness: 0.58,
    windX: 0.8,
    windY: 0.2,
    windSpeed: 12,
    lightingStrength: 1,
    silverLining: 0.45,
  },
  cirrus: {
    enabled: true,
    coverage: 0.18,
    density: 0.22,
    altitude: 7200,
    thickness: 900,
    scale: 1.4,
    detail: 0.42,
    softness: 0.76,
    windX: 0.35,
    windY: 0.9,
    windSpeed: 20,
    lightingStrength: 0.8,
    silverLining: 0.2,
  },
  fogEnabled: true,
  fogColor: { x: 0.64, y: 0.72, z: 0.8 },
  fogDensity: 0.008,
  fogHeightFalloff: 0.18,
  fogStartDistance: 28,
  fogMaxOpacity: 0.58,
  fogSunScattering: 0.7,
  lightingEnabled: true,
  lightingSource: 'followSky',
  lightingColor: { x: 1, y: 0.98, z: 0.94 },
  diffuseIntensity: 1,
  specularIntensity: 1,
  indirectLightingEnabled: true,
  indirectLightingMethod: 'autoSelect',
  indirectDiffuseIntensity: 1,
  reflectionIntensity: 1,
  emissiveContribution: 1,
  maximumTraceDistance: 200,
  surfaceCacheDetail: 1,
  allowHardwareRayTracing: true,
};

export const panelSourceControlFixture: SourceControlSnapshot = {
  available: true,
  repositoryRoot: 'C:/Projects/MountainVillage',
  branch: 'feature/alpine-lighting',
  detached: false,
  ahead: 2,
  behind: 0,
  files: [
    { path: 'Game/Lighting/AlpineEnvironment.cpp', indexState: 'modified', worktreeState: null },
    { path: 'Assets/Scenes/MountainVillage.arcscene', indexState: null, worktreeState: 'modified' },
    { path: 'Assets/Materials/M_Snow.arcmat', indexState: null, worktreeState: 'untracked' },
  ],
  error: '',
};

export const panelSettingsFixture: EditorSettingsSnapshot = {
  revision: 7,
  values: {
    'editor.autoSave': true,
    'editor.autoSaveMinutes': 5,
    'editor.theme': 'Arc Dark',
    'renderer.defaultQuality': 'High',
  },
  sources: {
    'editor.autoSave': 'user',
    'editor.autoSaveMinutes': 'user',
    'editor.theme': 'default',
    'renderer.defaultQuality': 'project',
  },
  restartRequired: [],
  schema: [
    {
      key: 'editor.autoSave',
      section: 'Editor',
      label: 'Auto Save',
      description: 'Periodically save dirty scene documents.',
      type: 'boolean',
      defaultValue: true,
      scopes: ['user', 'project'],
    },
    {
      key: 'editor.autoSaveMinutes',
      section: 'Editor',
      label: 'Auto Save Interval',
      description: 'Minutes between automatic saves.',
      type: 'number',
      defaultValue: 5,
      minimum: 1,
      maximum: 60,
      step: 1,
      scopes: ['user', 'project'],
    },
    {
      key: 'editor.theme',
      section: 'Editor',
      label: 'Theme',
      description: 'Editor color theme.',
      type: 'enum',
      defaultValue: 'Arc Dark',
      options: ['Arc Dark'],
      scopes: ['user'],
    },
    {
      key: 'renderer.defaultQuality',
      section: 'Renderer',
      label: 'Default Quality',
      description: 'Default viewport quality tier.',
      type: 'enum',
      defaultValue: 'High',
      options: ['Low', 'Medium', 'High', 'Ultra'],
      scopes: ['project'],
    },
  ],
};
