import type { EditorSettingDescriptor } from '../common/editorWorkflowTypes';
import {
  appleToolchainSettingKeys,
  defaultLinuxBuildEnvironment,
  licensedPlatformSettingKeys,
  linuxToolchainSettingKeys,
  webToolchainSettingKeys,
} from './platformToolchains';

export const platformSettingsDescriptors: EditorSettingDescriptor[] = [
  {
    key: linuxToolchainSettingKeys.buildEnvironment,
    section: 'Linux',
    label: 'Build Environment',
    description: 'Where ARC runs the Linux toolchain on this host.',
    type: 'enum',
    defaultValue: defaultLinuxBuildEnvironment(),
    options: ['auto', 'local', 'wsl'],
    optionLabels: { auto: 'Automatic', local: 'Local', wsl: 'WSL' },
    scopes: ['user'],
  },
  {
    key: linuxToolchainSettingKeys.wslDistribution,
    section: 'Linux',
    label: 'WSL Distribution',
    description: 'Optional WSL distribution name. Leave empty to use the default installed distribution.',
    type: 'string',
    defaultValue: '',
    scopes: ['user'],
    hostPlatforms: ['windows'],
  },
  {
    key: linuxToolchainSettingKeys.compilerPath,
    section: 'Linux',
    label: 'C++ Compiler',
    description: 'Linux clang++ or g++ executable. On Windows this is a path inside the selected WSL distribution.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    browsePath: false,
  },
  {
    key: linuxToolchainSettingKeys.sysrootPath,
    section: 'Linux',
    label: 'Sysroot',
    description: 'Optional target sysroot containing Linux headers and libraries.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    browsePath: false,
  },
  {
    key: appleToolchainSettingKeys.xcodePath,
    section: 'Apple',
    label: 'Xcode',
    description: 'Xcode developer directory. Local Apple builds require macOS and Xcode.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    hostPlatforms: ['macos'],
  },
  {
    key: appleToolchainSettingKeys.macosSdkPath,
    section: 'macOS',
    label: 'macOS SDK',
    description: 'SDK selected from the configured Xcode installation.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    readOnly: true,
    hostPlatforms: ['macos'],
  },
  {
    key: appleToolchainSettingKeys.iosDeviceSdkPath,
    section: 'iOS',
    label: 'iOS Device SDK',
    description: 'Device SDK selected from the configured Xcode installation.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    readOnly: true,
    hostPlatforms: ['macos'],
  },
  {
    key: appleToolchainSettingKeys.iosSimulatorSdkPath,
    section: 'iOS',
    label: 'iOS Simulator SDK',
    description: 'Simulator SDK selected from the configured Xcode installation.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    readOnly: true,
    hostPlatforms: ['macos'],
  },
  {
    key: appleToolchainSettingKeys.tvosDeviceSdkPath,
    section: 'tvOS',
    label: 'tvOS Device SDK',
    description: 'Device SDK selected from the configured Xcode installation.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    readOnly: true,
    hostPlatforms: ['macos'],
  },
  {
    key: appleToolchainSettingKeys.tvosSimulatorSdkPath,
    section: 'tvOS',
    label: 'tvOS Simulator SDK',
    description: 'Simulator SDK selected from the configured Xcode installation.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    readOnly: true,
    hostPlatforms: ['macos'],
  },
  {
    key: appleToolchainSettingKeys.visionosDeviceSdkPath,
    section: 'visionOS',
    label: 'visionOS Device SDK',
    description: 'Device SDK selected from the configured Xcode installation.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    readOnly: true,
    hostPlatforms: ['macos'],
  },
  {
    key: appleToolchainSettingKeys.visionosSimulatorSdkPath,
    section: 'visionOS',
    label: 'visionOS Simulator SDK',
    description: 'Simulator SDK selected from the configured Xcode installation.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    readOnly: true,
    hostPlatforms: ['macos'],
  },
  {
    key: webToolchainSettingKeys.emsdkPath,
    section: 'Web',
    label: 'Emscripten SDK',
    description: 'emsdk root containing the Emscripten compiler and CMake toolchain.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
  },
  {
    key: licensedPlatformSettingKeys.xboxGdkPath,
    section: 'Xbox',
    label: 'Microsoft GDK',
    description: 'Licensed Microsoft GDK installation root used by Xbox builds.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    hostPlatforms: ['windows'],
  },
  {
    key: licensedPlatformSettingKeys.playStationSdkPath,
    section: 'PlayStation',
    label: 'PlayStation SDK',
    description: 'Licensed PlayStation SDK installation root used by console builds.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    hostPlatforms: ['windows'],
  },
  {
    key: licensedPlatformSettingKeys.switchSdkPath,
    section: 'Nintendo Switch',
    label: 'Nintendo SDK',
    description: 'Licensed Nintendo development SDK installation root used by Switch builds.',
    type: 'string',
    format: 'path',
    defaultValue: '',
    scopes: ['user'],
    hostPlatforms: ['windows'],
  },
];

export const platformSettingKeys = platformSettingsDescriptors.map((descriptor) => descriptor.key);
