import type { Vec3 } from '../services/mockHost';

export type HostEntityId = {
  index: number;
  generation: number;
};

export type HostCloudLayer = {
  enabled: boolean;
  coverage: number;
  density: number;
  altitude: number;
  thickness: number;
  scale: number;
  detail: number;
  softness: number;
  windX: number;
  windY: number;
  windSpeed: number;
  lightingStrength: number;
  silverLining: number;
};

export type HostWorldEnvironment = {
  entity: HostEntityId;
  enabled: boolean;
  skyVisible: boolean;
  affectLighting: boolean;
  skySource: 'physicalAtmosphere' | 'hdri' | 'solidColor';
  solidColor: Vec3;
  hdriPath: string;
  hdriRotationDegrees: number;
  radianceIntensity: number;
  planetRadius: number;
  atmosphereRadius: number;
  rayleighStrength: number;
  mieStrength: number;
  ozoneStrength: number;
  atmosphereTint: Vec3;
  groundAlbedo: Vec3;
  mieAnisotropy: number;
  rayleighScaleHeight: number;
  mieScaleHeight: number;
  multiScatteringFactor: number;
  exposure: number;
  sunDiskSize: number;
  sunDiskIntensity: number;
  sunMode: 'manualLight' | 'geographic';
  timeMode: 'fixed' | 'simulated' | 'systemClock';
  latitudeDegrees: number;
  longitudeDegrees: number;
  northOffsetDegrees: number;
  year: number;
  month: number;
  day: number;
  localTimeHours: number;
  utcOffsetHours: number;
  playing: boolean;
  loopDay: boolean;
  timeScale: number;
  automaticSunLight: boolean;
  sunIntensityMultiplier: number;
  sunTemperatureMultiplier: number;
  moonEnabled: boolean;
  automaticMoonPhase: boolean;
  moonPhase: number;
  moonIntensity: number;
  moonAngularRadiusDegrees: number;
  starsEnabled: boolean;
  starDensity: number;
  starIntensity: number;
  starTwinkle: number;
  cloudsEnabled: boolean;
  cloudShadows: boolean;
  cumulus: HostCloudLayer;
  cirrus: HostCloudLayer;
  fogEnabled: boolean;
  fogColor: Vec3;
  fogDensity: number;
  fogHeightFalloff: number;
  fogStartDistance: number;
  fogMaxOpacity: number;
  fogSunScattering: number;
  lightingEnabled: boolean;
  lightingSource: 'followSky' | 'hdri' | 'constantColor';
  lightingColor: Vec3;
  diffuseIntensity: number;
  specularIntensity: number;
};
