cmake_minimum_required(VERSION 3.20)
project({{PROJECT_TOKEN}} LANGUAGES CXX)
find_package(ARC {{ENGINE_VERSION}} EXACT CONFIG REQUIRED COMPONENTS Runtime Server)
add_library({{PROJECT_TOKEN}}Runtime STATIC Source/{{PROJECT_TOKEN}}Runtime/Runtime.cpp)
target_compile_features({{PROJECT_TOKEN}}Runtime PUBLIC cxx_std_20)
target_link_libraries({{PROJECT_TOKEN}}Runtime PUBLIC ARC::Runtime)
add_library({{PROJECT_TOKEN}}Server STATIC Source/{{PROJECT_TOKEN}}Server/Server.cpp)
target_link_libraries({{PROJECT_TOKEN}}Server PUBLIC {{PROJECT_TOKEN}}Runtime ARC::Server)
add_executable({{PROJECT_TOKEN}}ServerApp Source/{{PROJECT_TOKEN}}Server/Main.cpp)
target_link_libraries({{PROJECT_TOKEN}}ServerApp PRIVATE {{PROJECT_TOKEN}}Server)
