#!/usr/bin/env python3
"""Generate ARC ECS component reflection metadata from dependency-free JSON schemas."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any


KINDS = {
    "bool": "boolean",
    "int": "signed_integer",
    "uint": "unsigned_integer",
    "float": "floating_point",
    "string": "string",
    "enum": "enumeration",
    "vector2": "vector2",
    "vector3": "vector3",
    "vector4": "vector4",
    "quaternion": "quaternion",
    "matrix": "matrix",
    "entity": "entity_reference",
    "asset": "asset_reference",
    "struct": "structure",
    "sequence": "sequence",
}


def parse_hex(value: str, digits: int, label: str) -> int:
    if len(value) != digits:
        raise ValueError(f"{label} must contain exactly {digits} hexadecimal digits")
    try:
        return int(value, 16)
    except ValueError as exception:
        raise ValueError(f"{label} is not hexadecimal") from exception


def load_schema(path: pathlib.Path) -> dict[str, Any]:
    schema = json.loads(path.read_text(encoding="utf-8"))
    namespace = schema.get("namespace")
    components = schema.get("components")
    if not isinstance(namespace, str) or not namespace:
        raise ValueError("schema namespace is required")
    if not isinstance(components, list):
        raise ValueError("schema components must be an array")

    type_ids: set[str] = set()
    canonical_names: set[str] = set()
    for component in components:
        type_name = component.get("type")
        type_id = component.get("id")
        if not isinstance(type_name, str) or not type_name:
            raise ValueError("component type is required")
        parse_hex(type_id, 32, f"{type_name} id")
        canonical = f"{namespace}.{type_name}"
        if type_id in type_ids:
            raise ValueError(f"duplicate component id {type_id}")
        if canonical in canonical_names:
            raise ValueError(f"duplicate component {canonical}")
        type_ids.add(type_id)
        canonical_names.add(canonical)

        field_ids: set[str] = set()
        field_names: set[str] = set()
        fields = component.get("fields", [])
        if not isinstance(fields, list) or len(fields) > 64:
            raise ValueError(f"{canonical} fields must be an array with at most 64 entries")
        for field in fields:
            name = field.get("name")
            field_id = field.get("id")
            kind = field.get("kind")
            if not isinstance(name, str) or not name:
                raise ValueError(f"{canonical} has a field without a name")
            parse_hex(field_id, 16, f"{canonical}.{name} id")
            if kind not in KINDS:
                raise ValueError(f"{canonical}.{name} uses unsupported kind {kind!r}")
            if field_id in field_ids or name in field_names:
                raise ValueError(f"{canonical} has a duplicate field id or name")
            field_ids.add(field_id)
            field_names.add(name)
    return schema


def split_type_id(value: str) -> tuple[str, str]:
    return value[:16], value[16:]


def flags_expression(field: dict[str, Any]) -> str:
    flags = field.get("flags", ["serialized", "editable", "prefab_override"])
    if not flags:
        return "reflected_field_flags::none"
    allowed = {"serialized", "replicated", "editable", "transient", "prefab_override"}
    unknown = set(flags) - allowed
    if unknown:
        raise ValueError(f"unknown field flags: {sorted(unknown)}")
    return " | ".join(f"reflected_field_flags::{flag}" for flag in flags)


def generate_cpp(schema: dict[str, Any]) -> str:
    namespace = schema["namespace"]
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/ecs_codegen.py. Do not edit.",
        "#include <arc/ecs/reflection.h>",
        "",
        "namespace arc::ecs",
        "{",
        "",
    ]
    for component in schema["components"]:
        type_name = component["type"]
        qualified = f"{namespace}::{type_name}"
        canonical = f"{namespace}.{type_name}"
        high, low = split_type_id(component["id"])
        fields = component.get("fields", [])
        lines.extend([
            "template <>",
            f"struct component_traits<{qualified}>",
            "{",
            "    static constexpr bool reflected = true;",
            f'    static constexpr std::string_view canonical_name = "{canonical}";',
            f"    static constexpr component_type_id id{{ 0x{high}ull, 0x{low}ull }};",
            f"    static constexpr std::array<component_field_descriptor, {len(fields)}> fields{{{{",
        ])
        for field in fields:
            display = field.get("display", field["name"].replace("_", " ").title())
            lines.append(
                "        { "
                f"0x{field['id']}ull, \"{field['name']}\", \"{display}\", "
                f"reflected_field_kind::{KINDS[field['kind']]}, {flags_expression(field)}"
                " },"
            )
        lines.extend([
            "    }};",
            "    static constexpr component_descriptor descriptor{",
            f'        id, canonical_name, "{component.get("display", type_name.replace("_component", "").replace("_", " ").title())}",',
            f"        {component.get('version', 1)}, sizeof({qualified}), alignof({qualified}), fields,",
            f"        {'true' if component.get('customSerialization', False) else 'false'},",
            f"        {'true' if component.get('customReplication', False) else 'false'}",
            "    };",
            "};",
            "",
        ])
    lines.extend(["} // namespace arc::ecs", ""])
    return "\n".join(lines)


def generate_typescript(schema: dict[str, Any]) -> str:
    records = []
    for component in schema["components"]:
        records.append({
            "id": component["id"],
            "canonicalName": f"{schema['namespace']}.{component['type']}",
            "displayName": component.get(
                "display", component["type"].replace("_component", "").replace("_", " ").title()
            ),
            "schemaVersion": component.get("version", 1),
            "fields": [
                {
                    "id": field["id"],
                    "name": field["name"],
                    "displayName": field.get("display", field["name"].replace("_", " ").title()),
                    "kind": field["kind"],
                    "flags": field.get("flags", ["serialized", "editable", "prefab_override"]),
                }
                for field in component.get("fields", [])
            ],
        })
    payload = json.dumps(records, indent=2)
    return (
        "// Generated by tools/ecs_codegen.py. Do not edit.\n"
        "export interface GeneratedEcsFieldMetadata {\n"
        "  id: string\n  name: string\n  displayName: string\n  kind: string\n  flags: string[]\n"
        "}\n"
        "export interface GeneratedEcsComponentMetadata {\n"
        "  id: string\n  canonicalName: string\n  displayName: string\n"
        "  schemaVersion: number\n  fields: GeneratedEcsFieldMetadata[]\n"
        "}\n\n"
        f"export const generatedEcsComponents = {payload} as const satisfies readonly GeneratedEcsComponentMetadata[]\n"
    )


def write_or_check(path: pathlib.Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", required=True, type=pathlib.Path)
    parser.add_argument("--cpp-output", type=pathlib.Path)
    parser.add_argument("--ts-output", type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    if not arguments.cpp_output and not arguments.ts_output:
        parser.error("at least one output is required")
    try:
        schema = load_schema(arguments.schema)
        valid = True
        if arguments.cpp_output:
            valid &= write_or_check(arguments.cpp_output, generate_cpp(schema), arguments.check)
        if arguments.ts_output:
            valid &= write_or_check(arguments.ts_output, generate_typescript(schema), arguments.check)
        if not valid:
            print("generated ECS metadata is stale", file=sys.stderr)
            return 2
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as exception:
        print(f"ECS code generation failed: {exception}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
