// Generated by tools/ecs_codegen.py. Do not edit.
export interface GeneratedEcsFieldMetadata {
  id: string
  name: string
  displayName: string
  kind: string
  flags: string[]
}
export interface GeneratedEcsComponentMetadata {
  id: string
  canonicalName: string
  displayName: string
  schemaVersion: number
  fields: GeneratedEcsFieldMetadata[]
}

export const generatedEcsComponents = [
  {
    "id": "a7c00000000000010000000000000001",
    "canonicalName": "arc::scene.name_component",
    "displayName": "Name",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "value",
        "displayName": "Value",
        "kind": "string",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      }
    ]
  },
  {
    "id": "a7c00000000000010000000000000002",
    "canonicalName": "arc::scene.transform_component",
    "displayName": "Transform",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "position",
        "displayName": "Location",
        "kind": "vector3",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000002",
        "name": "rotation",
        "displayName": "Rotation",
        "kind": "quaternion",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000003",
        "name": "scale",
        "displayName": "Scale",
        "kind": "vector3",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000004",
        "name": "world",
        "displayName": "World",
        "kind": "matrix",
        "flags": [
          "transient"
        ]
      },
      {
        "id": "0000000000000005",
        "name": "dirty",
        "displayName": "Dirty",
        "kind": "bool",
        "flags": [
          "transient"
        ]
      }
    ]
  },
  {
    "id": "a7c00000000000010000000000000003",
    "canonicalName": "arc::scene.tag_component",
    "displayName": "Tag",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "value",
        "displayName": "Value",
        "kind": "string",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      }
    ]
  },
  {
    "id": "a7c00000000000010000000000000004",
    "canonicalName": "arc::scene.active_component",
    "displayName": "Active",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "active",
        "displayName": "Active",
        "kind": "bool",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      }
    ]
  },
  {
    "id": "a7c00000000000010000000000000005",
    "canonicalName": "arc::scene.selection_component",
    "displayName": "Selection",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "selected",
        "displayName": "Selected",
        "kind": "bool",
        "flags": [
          "transient",
          "editable"
        ]
      }
    ]
  },
  {
    "id": "a7c00000000000010000000000000006",
    "canonicalName": "arc::scene.bounds_component",
    "displayName": "Bounds",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "local_bounds",
        "displayName": "Local Bounds",
        "kind": "struct",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000002",
        "name": "world_bounds",
        "displayName": "World Bounds",
        "kind": "struct",
        "flags": [
          "transient"
        ]
      },
      {
        "id": "0000000000000003",
        "name": "dirty",
        "displayName": "Dirty",
        "kind": "bool",
        "flags": [
          "transient"
        ]
      }
    ]
  },
  {
    "id": "a7c00000000000010000000000000007",
    "canonicalName": "arc::scene.camera_component",
    "displayName": "Camera",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "projection",
        "displayName": "Projection",
        "kind": "enum",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000002",
        "name": "fov_y_radians",
        "displayName": "Field of View",
        "kind": "float",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000003",
        "name": "near_plane",
        "displayName": "Near Clip",
        "kind": "float",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000004",
        "name": "far_plane",
        "displayName": "Far Clip",
        "kind": "float",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000005",
        "name": "orthographic_height",
        "displayName": "Orthographic Size",
        "kind": "float",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000006",
        "name": "active",
        "displayName": "Active Camera",
        "kind": "bool",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000007",
        "name": "clear_color",
        "displayName": "Clear Color",
        "kind": "vector4",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000008",
        "name": "exposure",
        "displayName": "Exposure",
        "kind": "struct",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      }
    ]
  },
  {
    "id": "a7c00000000000010000000000000008",
    "canonicalName": "arc::scene.mesh_renderer_component",
    "displayName": "Mesh Renderer",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "mesh",
        "displayName": "Mesh",
        "kind": "asset",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000002",
        "name": "material",
        "displayName": "Material",
        "kind": "asset",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000003",
        "name": "visible",
        "displayName": "Visible",
        "kind": "bool",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      },
      {
        "id": "0000000000000004",
        "name": "base_color_tint",
        "displayName": "Base Color Tint",
        "kind": "vector4",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      }
    ]
  },
  {
    "id": "a7c00000000000010000000000000009",
    "canonicalName": "arc::scene.virtual_mesh_renderer_component",
    "displayName": "Virtual Mesh Renderer",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000000a",
    "canonicalName": "arc::scene.skinned_mesh_renderer_component",
    "displayName": "Skinned Mesh Renderer",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000000b",
    "canonicalName": "arc::scene.lod_component",
    "displayName": "LOD",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000000c",
    "canonicalName": "arc::scene.instance_group_component",
    "displayName": "Instance Group",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000000d",
    "canonicalName": "arc::scene.render_layer_component",
    "displayName": "Render Layer",
    "schemaVersion": 1,
    "fields": [
      {
        "id": "0000000000000001",
        "name": "mask",
        "displayName": "Mask",
        "kind": "uint",
        "flags": [
          "serialized",
          "editable",
          "prefab_override"
        ]
      }
    ]
  },
  {
    "id": "a7c0000000000001000000000000000e",
    "canonicalName": "arc::scene.directional_light_component",
    "displayName": "Directional Light",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000000f",
    "canonicalName": "arc::scene.point_light_component",
    "displayName": "Point Light",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000010",
    "canonicalName": "arc::scene.spot_light_component",
    "displayName": "Spot Light",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000011",
    "canonicalName": "arc::scene.reflection_probe_component",
    "displayName": "Reflection Probe",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000012",
    "canonicalName": "arc::scene.irradiance_probe_component",
    "displayName": "Irradiance Probe",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000013",
    "canonicalName": "arc::scene.world_environment_component",
    "displayName": "World Environment",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000014",
    "canonicalName": "arc::scene.sky_atmosphere_component",
    "displayName": "Sky Atmosphere",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000015",
    "canonicalName": "arc::scene.celestial_sky_component",
    "displayName": "Celestial Sky",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000016",
    "canonicalName": "arc::scene.cloud_layers_component",
    "displayName": "Cloud Layers",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000017",
    "canonicalName": "arc::scene.environment_lighting_component",
    "displayName": "Environment Lighting",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000018",
    "canonicalName": "arc::scene.height_fog_component",
    "displayName": "Height Fog",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c00000000000010000000000000019",
    "canonicalName": "arc::scene.terrain_component",
    "displayName": "Terrain",
    "schemaVersion": 2,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000001a",
    "canonicalName": "arc::scene.water_component",
    "displayName": "Water",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000001b",
    "canonicalName": "arc::scene.vegetation_component",
    "displayName": "Vegetation",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000001c",
    "canonicalName": "arc::scene.decal_component",
    "displayName": "Decal",
    "schemaVersion": 1,
    "fields": []
  },
  {
    "id": "a7c0000000000001000000000000001d",
    "canonicalName": "arc::scene.area_light_component",
    "displayName": "Area Light",
    "schemaVersion": 1,
    "fields": []
  }
] as const satisfies readonly GeneratedEcsComponentMetadata[]
